//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSequence.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSequence.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument has an invalid type..
        /// </summary>
        internal static string ArgumentHasInvalidType {
            get {
                return ResourceManager.GetString("ArgumentHasInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of ContextBase.Current is not the ContextBase value installed by this ContextBaseScope..
        /// </summary>
        internal static string ContextModifiedInsideScope {
            get {
                return ResourceManager.GetString("ContextModifiedInsideScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ContextBaseScope is being disposed out of order..
        /// </summary>
        internal static string InterleavedContextScopes {
            get {
                return ResourceManager.GetString("InterleavedContextScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ContextBaseScope is being disposed on a different thread than it was created..
        /// </summary>
        internal static string InvalidContextScopeThread {
            get {
                return ResourceManager.GetString("InvalidContextScopeThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number is negative..
        /// </summary>
        internal static string PageNumberIsNegative {
            get {
                return ResourceManager.GetString("PageNumberIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent or child data could not be found..
        /// </summary>
        internal static string ParentOrChildDataNotFound {
            get {
                return ResourceManager.GetString("ParentOrChildDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent or child with the key &apos;{0}&apos; could not be found in the list of Class Model objects..
        /// </summary>
        internal static string ParentOrChildObjectInfoNotFound {
            get {
                return ResourceManager.GetString("ParentOrChildObjectInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DiagramNode of type DiagramSequenceNode only allows a node type of TypeInfo or MessageInfo..
        /// </summary>
        internal static string SequenceNodeAllowsOnlyTypeOrMessageInfo {
            get {
                return ResourceManager.GetString("SequenceNodeAllowsOnlyTypeOrMessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source or target with the key &apos;{0}&apos; could not be found in the list of Sequence objects..
        /// </summary>
        internal static string SourceOrTargetObjectInfoNotFound {
            get {
                return ResourceManager.GetString("SourceOrTargetObjectInfoNotFound", resourceCulture);
            }
        }
    }
}
